app:
  config-file-path: /app/config/config.yaml

environment-variables:
  application:
    version: @project.version@

logging:
  level:
    org:
      springframework: OFF

management:
  endpoints:
    web:
      exposure:
        include: health